version: '3.8'

services:
  # FastAPI Backend
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  # Streamlit Frontend
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://fastapi:8000
    volumes:
      - ./frontend:/app
      - ./.env:/app/.env
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 